// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

#include "UnityCG.cginc"	
#include "Assets/Raytracing/Tet.hlsl"
#include "Assets/Raytracing/RayTracingStructs.hlsl"

RWStructuredBuffer<Tet> ret;
RWStructuredBuffer<HitInfo> hitInfo;

[numthreads(1,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
	float4x4 tet = {
		1,-1,0,0,
		-1,-1,0,0,
		0,1,1,0,
		0,1,-1,0
	};
	Tet t = (Tet)0;
	t.from_points(tet);
	ret[0] = t;



	Ray r;
	r.origin = float4(0,0,-5,0);
	r.dir = float4(0, 0.1, 1, 0);
	hitInfo[0].dst = 6969;
	hitInfo[0] = t.intersection(r);
}
